name: Publish Docs

on:
  workflow_dispatch:
  push:
    branches:
      - release

permissions: write-all

jobs:
  package:
    name: Package
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 18
      
      - name: Frontend dependencies
        run: |
          npm i -g pnpm
          pnpm install

      - name: Build application
        run: pnpm build

      - name: Upload web app
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./build
  release:
    name: Publish
    runs-on: ubuntu-latest
    needs:
      - package
    steps:
      - name: Publish web app
        uses: actions/deploy-pages@v1
